### ISSUE TITLE
Enhancement Request : MOL file support

### ISSUE THREAD

**Issue by runette** [JensKrumsieck/ChemSharp#35]
Is there a reason there is no .MOL file format support? It would be very useful - for instance, this is how compounds come from ChemSpider

**Comment by JensKrumsieck** [comment]
I added .MOL File support in https://github.com/JensKrumsieck/ChemSharp/commit/9dab1da021a084072612d1f13c01f1829bb4051f

ChemSpider does not add implicit hydrogens to MOL Files which contain a 2D molecule so i did not add them, too. In 3D everything works as expected.

**Comment by runette** [comment]
Cool. I will give it a try. Thanks

**Comment by runette** [comment]
From an initial test - it seems to be working very well thanks
